spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_seller?useSSL=false
    username: root
    password: giveUrPassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa.hibernate.ddl_auto: create